on:
  push:
    paths:
      - 'version/trojan-r'

name: trojan-r
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set env
        run: |
          echo "VERSION=$(cat "version/trojan-r" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash
      
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt,clippy,rls

      - name: Build
        run: |
          sudo apt install -y git wget gcc g++ make automake musl-tools
          cp src/build/trojan-r.sh $PWD/trojan-r.sh && chmod +x trojan-r.sh && ./trojan-r.sh
       
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./release/*
            
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set env
        run: |
          echo "VERSION=$(cat "version/trojan-r" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/trojan-r/* $PWD
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: charlieethan
          password: ${{ secrets.PACKAGE_TOKEN }}
      
      - name: Build latest
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            charlieethan/trojan-r:latest
            ghcr.io/charlieethan/trojan-r:latest

      - name: Build tag
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            charlieethan/trojan-r:${{ env.VERSION }}
            ghcr.io/charlieethan/trojan-r:${{ env.VERSION }}
           
  test:
     needs: [build,push]
     runs-on: ubuntu-latest
     steps:
       
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup variables
        run: |
          echo "VERSION=$(cat "version/trojan-r" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint /usr/bin/trojan-r charlieethan/trojan-r:latest --version
          docker run --rm --entrypoint /usr/bin/trojan-r charlieethan/trojan-r:${{ env.VERSION }} --version

          docker run --rm --entrypoint /usr/bin/trojan-r ghcr.io/charlieethan/trojan-r:latest --version
          docker run --rm --entrypoint /usr/bin/trojan-r ghcr.io/charlieethan/trojan-r:${{ env.VERSION }} --version
