on:
  push:
    paths:
      - 'version/xray'

name: xray
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env
        run: |
          echo "GOLANG=$(wget -qO- https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep 'version' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
          echo "VERSION=$(cat "version/xray" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Install Golang
        uses: actions/setup-go@v2
        with: 
          go-version: ${{ env.GOLANG }}

      - name: Start build
        run: |
          cp src/build/xray.sh $PWD/xray.sh && chmod +x xray.sh && ./xray.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./release/*

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/xray" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/xray/* $PWD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: charlieethan
          password: ${{ secrets.PACKAGE_TOKEN }}
      
      - name: Build latest
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            charlieethan/xray:latest
            ghcr.io/charlieethan/xray:latest

      - name: Build tag
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            charlieethan/xray:${{ env.VERSION }}
            ghcr.io/charlieethan/xray:${{ env.VERSION }}

  test:
    needs: [build,push]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/xray" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint /usr/bin/xray charlieethan/xray:latest -version
          docker run --rm --entrypoint /usr/bin/xray charlieethan/xray:${{ env.VERSION }} -version

          docker run --rm --entrypoint /usr/bin/xray ghcr.io/charlieethan/xray:latest -version
          docker run --rm --entrypoint /usr/bin/xray ghcr.io/charlieethan/xray:${{ env.VERSION }} -version